spring.application.name=api-gateway
server.port=8765

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

logging.pattern.console=%C{1} [%-5level] %d{HH:mm:ss} - %msg%n

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

#ararara
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=false
spring.cloud.gateway.globalcors.cors-configurations.[/**].maxAge=3600

spring.cloud.gateway.routes[0].id=users-auth-route
spring.cloud.gateway.routes[0].uri=lb://users
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=users-api-route
spring.cloud.gateway.routes[1].uri=lb://users
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**

spring.cloud.gateway.routes[2].id=profile-api-route
spring.cloud.gateway.routes[2].uri=lb://profile
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/profile/**

spring.cloud.gateway.routes[3].id=pvz-api-route
spring.cloud.gateway.routes[3].uri=lb://profile
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/pvz/**

spring.cloud.gateway.routes[4].id=employee-api-route
spring.cloud.gateway.routes[4].uri=lb://profile
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/employee/**

spring.cloud.gateway.routes[5].id=shift-api-route
spring.cloud.gateway.routes[5].uri=lb://profile
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/shift/**

spring.cloud.gateway.routes[6].id=image-api-route
spring.cloud.gateway.routes[6].uri=lb://profile
spring.cloud.gateway.routes[6].predicates[0]=Path=/image/**

spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.timeout=60000

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.reactor.netty=DEBUG
logging.level.reactor.netty.http.server=DEBUG
logging.level.org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping=DEBUG
logging.level.org.springframework.web.reactive.DispatcherHandler=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.reactive=DEBUG