### 1. Аутентификация и управление токенами

### 1.1 Вход в систему (получение JWT)
POST http://localhost:8765/auth/sign-in
Content-Type: application/json

{
  "email": "4057163@mail.ru",
  "password": "11111111"
}

> {% client.global.set("token", response.body.token);
    client.global.set("refreshToken", response.body.refreshToken);
    client.log("Access Token: " + response.body.token);
    client.log("Refresh Token: " + response.body.refreshToken);
%}

### 1.2 Обновление access token
POST http://localhost:8765/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### 1.3 Выход (инвалидация текущего access token)
POST http://localhost:8765/auth/logout
Authorization: Bearer {{token}}

### 1.4 Полный выход со всех устройств (инвалидация всех refresh токенов пользователя)
POST http://localhost:8765/auth/fullLogout/1
Authorization: Bearer {{token}}

### 2. Пользователи (UserController)

### 2.1 Получить пользователя по фамилии (для внутренних сервисов)
GET http://localhost:8765/api/users/secondName?secondName=Иванов

### 2.2 Получить пользователя по ID (некорректное использование @RequestParam, но по коду)
GET http://localhost:8765/api/users/1?id=1

### 2.3 Получить пользователя по email
GET http://localhost:8765/api/users/email?email=user@example.com

### 2.4 Регистрация нового пользователя
POST http://localhost:8765/api/users/registration
Content-Type: application/json

{
  "name": "ARa",
  "secondName": "qwe",
  "surName": "Петров",
  "password": "11111111",
  "email": "4057163@mail.ru",
  "birthDay": "1995-05-15"
}

### 2.5 Подтверждение регистрации по коду
POST http://localhost:8765/api/users/confirm-registration?code=7A4845

### 2.6 Повторная отправка кода подтверждения
POST http://localhost:8765/api/users/resend-confirm-registration?email=djkslsdkmds@mail.ru

### 2.7 Отправка кода для сброса пароля
POST http://localhost:8765/api/users/send-password-resetCode?email=user@example.com

### 2.8 Сброс пароля с использованием кода
POST http://localhost:8765/api/users/reset-password-with-code?email=user@example.com&code=123456&newPassword=newPass123

### 2.9 Отправка кода для смены email (требуется авторизация)
POST http://localhost:8765/api/users/send-email-reset-code?email=current@example.com&newEmail=new@example.com
Authorization: Bearer {{token}}

### 2.10 Повторная отправка кода для смены email (по ожидающему email)
POST http://localhost:8765/api/users/resend-email-resetCode?pendingEmail=new@example.com

### 2.11 Обновление пароля (требуется авторизация)
PUT http://localhost:8765/api/users/update-user-password/1?newPassword=newPass&currenPassword=oldPass
Authorization: Bearer {{token}}

### 2.12 Подтверждение смены email по коду (требуется авторизация)
POST http://localhost:8765/api/users/confirm-email-change/1?code=123456
Authorization: Bearer {{token}}

### 2.13 Обновление ролей пользователя (требуется авторизация)
PUT http://localhost:8765/api/users/update-roles/17
Authorization: Bearer {{token}}
Content-Type: application/json

["ROLE_OWNER_PVZ"]

### 2.14 Получить всех пользователей (только для ADMIN)
GET http://localhost:8765/api/users/get-all-users
Authorization: Bearer {{token}}

### 2.15 Изменить статус аккаунта (вкл/выкл) (только для ADMIN)
PUT http://localhost:8765/api/users/changeAccountStatus/1?newAccountStatus=false
Authorization: Bearer {{token}}

### 2.16 Блокировка аккаунта (только для ADMIN)
PUT http://localhost:8765/api/users/accountBlocking/2?newAccountStatus=true
Authorization: Bearer {{token}}

### 2.17 Обновить имя (требуется авторизация)
PUT http://localhost:8765/api/users/updateName/1?newName=Текхн
Authorization: Bearer {{token}}

### 2.18 Обновить фамилию (требуется авторизация)
PUT http://localhost:8765/api/users/updateSecondName/16?newSecondName=Техник
Authorization: Bearer {{token}}

### 3. Профиль (ProfileController)

### 3.1 Получить свой профиль (требуется авторизация)
GET http://localhost:8765/profile/api/profile/myProfile/1
Authorization: Bearer {{token}}

### 3.1.2 Найту профиль друга поп почте
GET http://localhost:8765/profile/api/profile/findProfile?email=4057163@mail.ru
Authorization: Bearer {{token}}

### 3.2 Установить/заменить аватар (требуется авторизация)
POST http://localhost:8765/profile/api/profile/setAvatar/1
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test-avatar.jpg"
Content-Type: image/jpeg

< ./test-photo1.jpg
--WebAppBoundary--

### 3.3 Удалить аватар (требуется авторизация)
DELETE http://localhost:8765/profile/api/profile/deleteAvatar/1
Authorization: Bearer {{token}}

### 3.4 Получить изображение (пример)
GET http://localhost:8765/profile/image/11
Authorization: Bearer {{token}}

### 3.5 Получить список ПВЗ пользователя
GET http://localhost:8765/profile/api/profile/getMyPvzShort/1
Authorization: Bearer {{token}}

### 3.5 Получить Детальные данные  ПВЗ пользователя
GET http://localhost:8765/profile/api/profile/getPvzDetailsDto/1
Authorization: Bearer {{token}}

### 4. Сотрудники (EmployeeController)

### 4.1 Создать сотрудника (требуется авторизация)
POST http://localhost:8765/profile/api/employee/createEmployee/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Ара",
  "secondName": "Техник",
  "surName": "Петров",
  "phone": "+7189197140",
  "fixedRatePerHour": 500.00
}

### 4.2 Удалить сотрудника по ID (требуется авторизация)
DELETE http://localhost:8765/profile/api/employee/deleteEmployee/4
Authorization: Bearer {{token}}

### 4.3 Поиск сотрудников в ПВЗ (по имени, фамилии, отчеству)
GET http://localhost:8765/profile/api/employee/search/1?name=Настя&secondName=&surName=
Authorization: Bearer {{token}}

### 5. Пункты выдачи (PvzController)

### 5.1 Создать ПВЗ (требуется авторизация)
POST http://localhost:8765/profile/api/pvz/createPvz
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "ПВЗ на test",
  "address": "ул. tessst 19"
}

### 5.2 Обновить название ПВЗ (требуется авторизация)
PUT http://localhost:8765/profile/api/pvz/updateNamePvz/1?newName=ПВЗ на Чехова
Authorization: Bearer {{token}}

### 5.3 Обновить адрес ПВЗ (требуется авторизация)
PUT http://localhost:8765/profile/api/pvz/updateAddressPvz/1?newName=ул. Гагарина, д. 5
Authorization: Bearer {{token}}

### 5.4 Удалить ПВЗ по ID (требуется авторизация)
DELETE http://localhost:8765/profile/api/pvz/deletePvz/1
Authorization: Bearer {{token}}

### 6. Смены (ShiftController)

### 6.1 Создать смену (требуется авторизация)
POST http://localhost:8765/profile/api/shift/createShift
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "employeeId": "1",
  "scheduledStartTime": "2026-02-03T09:00:00",
  "scheduledEndTime": "2026-02-03T18:00:00"
}
### 6.2 Добавить бонус к смене (требуется авторизация)
POST http://localhost:8765/profile/api/shift/addBonus/1
Authorization: Bearer {{token}}
Content-Type: application/json

500.00

### 6.3 Добавить штраф к смене (требуется авторизация)
POST http://localhost:8765/profile/api/shift/addPenalty/1
Authorization: Bearer {{token}}
Content-Type: application/json

200.00

### 6.4 Добавить причину штрафа к смене (требуется авторизация)
POST http://localhost:8765/profile/api/shift/addPenaltyReason/1
Authorization: Bearer {{token}}
Content-Type: application/json

"опоздал"

### 6.6 Установить фактическое время начала смены (через тело запроса)
POST http://localhost:8765/profile/api/shift/actualStartTime/1
Authorization: Bearer {{token}}
Content-Type: application/json

"2026-03-04T10:00:00"

### 6.7 Установить фактическое время окончания смены (через тело запроса)
POST http://localhost:8765/profile/api/shift/actualEndTime/1
Authorization: Bearer {{token}}
Content-Type: application/json

"2026-03-04T17:00:00"

### 6.8 Получить расчёт зарплаты за смену
GET http://localhost:8765/profile/api/shift/calculatePay/1
Authorization: Bearer {{token}}

### 6.9 Обновить статус смены (PLANNED, COMPLETED, MISSED) через тело запроса
PUT http://localhost:8765/profile/api/shift/updateStatus/1
Authorization: Bearer {{token}}
Content-Type: application/json

"COMPLETED"

### 6.10 Обновить сотрудника для смены
PUT http://localhost:8765/profile/api/shift/updateEmployeeForShift/1/2
Authorization: Bearer {{token}}

### 6.11 Получить полную информацию о смене по ID (требуется авторизация)
GET http://localhost:8765/profile/api/shift/getFullShift/1
Authorization: Bearer {{token}}

### 6.12 Получить список смен для ПВЗ (требуется авторизация)
GET http://localhost:8765/profile/api/shift/getShiftsByPvz/1
Authorization: Bearer {{token}}

### 6.13 Получить смены сотрудника в конкретном ПВЗ (требуется авторизация)
GET http://localhost:8765/profile/api/shift/employee/1/pvz/1
Authorization: Bearer {{token}}

