spring.application.name=email-service
server.port=0

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
logging.pattern.console=%C{1} [%-5level] %d{HH:mm:ss} - %msg%n
eureka.instance.instance-id=${spring.application.name}:${spring.cloud.client.hostname}:${random.uuid}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=9197195@gmail.com
spring.mail.password=suhjonzyinoerula

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.kafka.bootstrap-servers=kafka:29092
